leftnav:
- identifier: 1744d4f8-8065-4bf0-be85-12784ffa7a61
  name: 'Part 1: DNA Replication and Repair'
  pageRef: /external-resources/part-1-dna-replication-and-repair_1744d4f8-8065-4bf0-be85-12784ffa7a61
  weight: 10
- identifier: ca93481b-6357-4a9c-aadc-a8399c741076
  name: 'Part 2: Transcription and Transposition'
  pageRef: /external-resources/part-2-transcription-and-transposition_ca93481b-6357-4a9c-aadc-a8399c741076
  weight: 20
- identifier: 65fc12af-5cd7-4d63-ae3a-7f0174e227c4
  name: 'Part 3: RNA Processing and Translation'
  pageRef: /external-resources/part-3-rna-processing-and-translation_65fc12af-5cd7-4d63-ae3a-7f0174e227c4
  weight: 30
